# Generated by Django 5.2.4 on 2025-07-05 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='created_at',
        ),
        migrations.AddField(
            model_name='property',
            name='purpose',
            field=models.CharField(choices=[('buy', 'Buy'), ('rent', 'Rent'), ('sell', 'Sell')], default='buy', max_length=10),
        ),
        migrations.AlterField(
            model_name='property',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='property_images/'),
        ),
        migrations.AlterField(
            model_name='property',
            name='location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='property',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
