# Generated by Django 5.2.4 on 2025-07-05 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_remove_property_description_remove_property_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='description',
            field=models.TextField(default='No Descriptions yet', max_length=100000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='property_images/'),
        ),
        migrations.AddField(
            model_name='property',
            name='location',
            field=models.CharField(default='No location provided', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='purpose',
            field=models.CharField(choices=[('buy', 'Buy'), ('rent', 'Rent'), ('sell', 'Sell')], default='buy', max_length=10),
        ),
        migrations.AddField(
            model_name='property',
            name='title',
            field=models.CharField(default=0.0, max_length=100),
            preserve_default=False,
        ),
    ]
