# Generated by Django 5.2.4 on 2025-07-06 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_alter_property_description_alter_property_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='properties/'),
        ),
        migrations.AlterField(
            model_name='property',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(blank=True, choices=[('land', 'Land'), ('plot', 'Plot'), ('shop', 'Shop'), ('house', 'House'), ('kothi', 'Kothi'), ('hotel', 'Hotel')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='purpose',
            field=models.CharField(blank=True, choices=[('buy', 'Buy'), ('rent', 'Rent'), ('sell', 'Sell')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
